//MYSQL
#Enables the DATA.SQL for DATABASE
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
#Atera a estrutura da tabela caso a entidade tenha mudança

spring.jpa.hibernate.ddl-auto=update

#Acessa o banco de dados
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/livraria
#Usuário do banco de dados
spring.datasource.username=rooter
#senha do banco de dados
spring.datasource.password=Root@2024
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret:4f7d9c8b2a1e6f5d3c7b9a8e1f2d4c6b7a9e3f5d8c1b6a4e7f9d2c5b8a1e6f3
app.jwt.expiration:86400000
# Configuração de origens permitidas para o CORS (ex: para permitir chamadas do Frontend)
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173