import { Book, Author, Category, Review } from '../types';

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Ficção e Literatura', slug: 'fiction', iconName: 'BookOpen', booksCount: 7 },
  { id: 'cat-2', name: 'Ciência e Tecnologia', slug: 'sci-tech', iconName: 'Cpu', booksCount: 3 },
  { id: 'cat-3', name: 'Desenvolvimento Pessoal', slug: 'self-improvement', iconName: 'Sparkles', booksCount: 3 },
  { id: 'cat-4', name: 'Negócios e Finanças', slug: 'business-finance', iconName: 'TrendingUp', booksCount: 3 },
  { id: 'cat-5', name: 'Biografia e História', slug: 'biography-history', iconName: 'History', booksCount: 3 },
];

export const mockAuthors: Author[] = [
  { id: 'aut-1', name: 'Pepetela', bio: 'Renomado escritor angolano, vencedor do Prémio Camões. Suas obras abordam detalhadamente a história contemporânea e os desafios sociais de Angola.', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80', booksCount: 3 },
  { id: 'aut-2', name: 'Mia Couto', bio: 'Um dos escritores moçambicanos mais célebres internacionalmente, biólogo e jornalista. Célebre pelo seu realismo mágico e reinvenção poética da língua portuguesa.', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80', booksCount: 1 },
  { id: 'aut-3', name: 'Ondjaki', bio: 'Pseudónimo de Ndalu de Almeida, destacado autor e poeta angolano. Com estilo sensível e nostálgico, pinta retratos vívidos do cotidiano luandense.', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80', booksCount: 1 },
  { id: 'aut-4', name: 'José Eduardo Agualusa', bio: 'Escritor e jornalista angolano. Suas narrativas misturam ficção, sonho e história, traduzidas para mais de trinta idiomas em todo o mundo.', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80', booksCount: 2 },
  { id: 'aut-5', name: 'Agostinho Neto', bio: 'Primeiro Presidente de Angola, médico e poeta maior nacional. Sua poesia seminal expressou o grito de libertação e de esperança do povo africano.', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80', booksCount: 1 },
  { id: 'aut-6', name: 'Manuel Rui', bio: 'Escritor seminal angolano, autor da letra do Hino Nacional. Mestre da sátira e do humor, sua obra captura o espírito vibrante do povo suburbano angolano.', avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80', booksCount: 1 },
  { id: 'aut-7', name: 'Dr. Stuart Russell', bio: 'Cientista de computação proeminente, pesquisador e professor especialista em robótica inteligente e sistemas éticos e robustos.', avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80', booksCount: 2 },
  { id: 'aut-8', name: 'James Clear', bio: 'Especialista em formação de hábitos de alto desempenho de nível internacional, criador do modelo prático de micro-mudanças de 1% ao dia.', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80', booksCount: 2 },
  { id: 'aut-9', name: 'Robert Kiyosaki', bio: 'Investidor norte-americano que revolucionou o entendimento mundial sobre literacia de ativos financeiros de investimento e inteligência de caixa.', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80', booksCount: 2 },
  { id: 'aut-10', name: 'Nelson Mandela', bio: 'Líder histórico mundial revolucionário e ex-presidente da África do Sul, laureado com o Prémio Nobel da Paz por sua resistência ao Apartheid.', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80', booksCount: 1 }
];

export const mockBooks: Book[] = [
  {
    id: 'book-1',
    title: 'Mayombe',
    authorId: 'aut-1',
    categoryId: 'cat-1',
    description: 'Uma obra-prima da literatura angolana que retrata de forma brilhante as vidas, ideais políticos, conflitos éticos e as relações humanas dos guerrilheiros combatentes na mística floresta de Cabinda durante a luta de libertação nacional contra o colonialismo.',
    price: 6500,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-emerald-800 via-green-905 to-stone-900',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 25,
    pages: 240,
    publishedDate: '1980-05-18',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 142,
    isbn: '978-972-21-0814-1',
    publisher: 'União dos Escritores Angolanos',
    sellerType: 'publisher',
    sellerName: 'Editora Chá de Caxinde'
  },
  {
    id: 'book-2',
    title: 'Terra Sonâmbula',
    authorId: 'aut-2',
    categoryId: 'cat-1',
    description: 'Considerada uma das dez melhores obras da literatura africana do século XX, narra de maneira poética e tocante a fantástica travessia do menino Muidinga e do velho Tuahir por Moçambique devastrada pela guerra, guiados pelas anotações de um diário misterioso.',
    price: 7200,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-amber-800 via-amber-900 to-red-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 18,
    pages: 220,
    publishedDate: '1992-10-12',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 96,
    isbn: '978-972-21-0850-9',
    publisher: 'Caminho Editorial',
    sellerType: 'publisher',
    sellerName: 'Editora Mulemba'
  },
  {
    id: 'book-3',
    title: 'Bom Dia Camaradas',
    authorId: 'aut-3',
    categoryId: 'cat-1',
    description: 'Um romance envolvente que retrata a infância em Luanda na década de 1990 sob o olhar singelo e bem-humorado de um garoto, registrando as transformações sociais angolanas de transição e o calor dos professores cooperantes cubanos.',
    price: 5500,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1531988042231-d39a9cc12a9a?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-orange-850 via-amber-900 to-amber-955',
    type: 'physical',
    formats: ['physical'],
    stock: 8,
    pages: 160,
    publishedDate: '2001-04-15',
    bestSeller: false,
    newRelease: false,
    reviewsCount: 64,
    isbn: '978-989-67-1049-5',
    publisher: 'Editora Caminho Luanda',
    sellerType: 'bookstore',
    sellerName: 'Sebo do Sambizanga',
    city: 'Luanda',
    state: 'LA'
  },
  {
    id: 'book-4',
    title: 'O Vendedor de Passados',
    authorId: 'aut-4',
    categoryId: 'cat-1',
    description: 'Félix Ventura vende passados luxuosos, memórias fabricadas e árvores genealógicas imponentes para a nova elite rica de Luanda, até que surge um jornalista estrangeiro misterioso pedindo um passado inesperado.',
    price: 6800,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1463320305860-ac2a7a3a30c5?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-indigo-900 via-indigo-950 to-purple-955',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 14,
    pages: 180,
    publishedDate: '2004-11-02',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 110,
    isbn: '978-972-21-1634-4',
    publisher: 'Publicações Dom Quixote',
    sellerType: 'reader',
    sellerName: 'António Luando',
    condition: 'used_very_good',
    conditionNotes: 'Miolo limpo, sem marcações ou páginas dobradas. Em estado espetacular de conservação.',
    city: 'Benguela',
    state: 'BG'
  },
  {
    id: 'book-5',
    title: 'Quem Me Dera Ser Onda',
    authorId: 'aut-6',
    categoryId: 'cat-1',
    description: 'Uma impagável e icônica sátira angolana sobre o confinamento de um porco num apartamento em um prédio habitacional no centro de Luanda, servindo de metáfora crítica e humorística para a sociedade pós-independência.',
    price: 4200,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-sky-800 via-teal-900 to-neutral-900',
    type: 'both',
    formats: ['physical', 'pdf'],
    stock: 35,
    pages: 96,
    publishedDate: '1982-01-20',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 185,
    isbn: '978-972-21-0816-5',
    publisher: 'União de Escritores UEA',
    sellerType: 'bookstore',
    sellerName: 'Livraria Kilamba',
    city: 'Luanda',
    state: 'LA'
  },
  {
    id: 'book-6',
    title: 'Sagrada Esperança',
    authorId: 'aut-5',
    categoryId: 'cat-1',
    description: 'A coletânea seminal de poesias políticas de Agostinho Neto, o maior poeta nacional. Versos que expressam em tom lírico e combativo a resistência, o sofrimento coletivo e a certeza inabalável do nascer de uma nova angolanidade.',
    price: 4900,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1447069387593-a5de0862481e?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-red-950 via-zinc-900 to-stone-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 50,
    pages: 145,
    publishedDate: '1974-06-15',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 220,
    isbn: '978-972-21-0820-2',
    publisher: 'União dos Escritores Angolanos',
    sellerType: 'publisher',
    sellerName: 'Editora UEA Luanda'
  },
  {
    id: 'book-7',
    title: 'O Legado de Njinga Mbandi',
    authorId: 'aut-4',
    categoryId: 'cat-5',
    description: 'Uma excelente investigação biográfica sobre Njinga Mbandi, a rainha angolana guerreira que liderou habilmente o Ndongo e Matamba, resistindo com táticas diplomáticas e militares únicas contra a expansão colonial do século XVII.',
    price: 8500,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-amber-700 via-amber-800 to-yellow-950',
    type: 'both',
    formats: ['physical', 'pdf'],
    stock: 15,
    pages: 256,
    publishedDate: '2012-07-07',
    bestSeller: false,
    newRelease: false,
    reviewsCount: 38,
    isbn: '978-989-67-1014-3',
    publisher: 'Editora Mulemba',
    sellerType: 'publisher',
    sellerName: 'Distribuidora Mulemba'
  },
  {
    id: 'book-8',
    title: 'Caminho para a Liberdade',
    authorId: 'aut-10',
    categoryId: 'cat-5',
    description: 'A clássica e monumental autobiografia histórica de Nelson Mandela, descrevendo em minúcias sua infância tribal, ativismo político no ANC, os 27 anos na prisão e a liderança heroica pela reconciliação na África do Sul.',
    price: 11000,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-sky-700 via-indigo-950 to-stone-900',
    type: 'physical',
    formats: ['physical'],
    stock: 6,
    pages: 512,
    publishedDate: '1994-11-20',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 165,
    isbn: '978-0-349-10752-3',
    publisher: 'Little Brown Booker',
    sellerType: 'bookstore',
    sellerName: 'Livraria Lello Angola',
    city: 'Lubango',
    state: 'HU'
  },
  {
    id: 'book-9',
    title: 'A Geração da Utopia',
    authorId: 'aut-1',
    categoryId: 'cat-1',
    description: 'Um romance formidável que percorre trinta anos da história contemporânea de Angola, acompanhando quatro conhecidos desde a vivência estudantil até os complexos caminhos das decisões de Estado pós-independência.',
    price: 7500,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-violet-850 via-rose-950 to-neutral-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 12,
    pages: 310,
    publishedDate: '1992-06-18',
    bestSeller: false,
    newRelease: true,
    reviewsCount: 43,
    isbn: '978-972-21-0730-4',
    publisher: 'União dos Escritores UEA',
    sellerType: 'author',
    sellerName: 'Pepetela'
  },
  {
    id: 'book-10',
    title: 'Código Limpo (Clean Code)',
    authorId: 'aut-7',
    categoryId: 'cat-2',
    description: 'A bíblia clássica indispensável para qualquer engenheiro e programador. Ensina as melhores práticas de design de padrões de software, legibilidade avançada, testes limpos e modularização de código ágil.',
    price: 18500,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-slate-800 via-indigo-950 to-neutral-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 14,
    pages: 420,
    publishedDate: '2008-08-11',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 310,
    isbn: '978-85-7608-264-5',
    publisher: 'Alta Books Editora',
    sellerType: 'bookstore',
    sellerName: 'Livraria das Nações',
    city: 'Luanda',
    state: 'LA'
  },
  {
    id: 'book-11',
    title: 'Inteligência Artificial moderna',
    authorId: 'aut-7',
    categoryId: 'cat-2',
    description: 'A referência mais respeitada e abrangente sobre inteligência artificial no planeta, cobrindo com solidez desde os algoritmos tradicionais de busca até agentes heurísticos, processamento natural e redes neurais profundas.',
    price: 26000,
    rating: 4.9,
    coverImage: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-purple-900 via-violet-950 to-blue-950',
    type: 'both',
    formats: ['physical', 'pdf'],
    stock: 8,
    pages: 1100,
    publishedDate: '2020-04-20',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 88,
    isbn: '978-85-216-3720-3',
    publisher: 'LTC Editora Técnica',
    sellerType: 'publisher',
    sellerName: 'LTC Editora'
  },
  {
    id: 'book-12',
    title: 'Hábitos Atómicos',
    authorId: 'aut-8',
    categoryId: 'cat-3',
    description: 'Um extraordinário e dinâmico guia de liderança pessoal que propõe um modelo científico de fácil aplicação: melhore 1% ao dia e colha resultados gigantescos em suas rotinas a longo prazo.',
    price: 9500,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-orange-655 via-yellow-700 to-amber-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 45,
    pages: 320,
    publishedDate: '2018-10-16',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 420,
    isbn: '978-989-66-8575-1',
    publisher: 'Lua de Papel Editores',
    sellerType: 'publisher',
    sellerName: 'Editora Mulemba'
  },
  {
    id: 'book-13',
    title: 'O Poder do Hábito',
    authorId: 'aut-8',
    categoryId: 'cat-3',
    description: 'O influente repórter do NY Times traz dados científicos envolventes que explicam por que os hábitos existem, como se solidificam no cérebro e como podemos alterá-los para transformar nossa rotina profissional.',
    price: 8900,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-teal-700 via-cyan-805 to-sky-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 20,
    pages: 408,
    publishedDate: '2012-02-28',
    bestSeller: false,
    newRelease: false,
    reviewsCount: 198,
    isbn: '978-85-390-0411-9',
    publisher: 'Editora Sextante Ltda',
    sellerType: 'reader',
    sellerName: 'Teresa Samba',
    condition: 'used_good',
    conditionNotes: 'Capa mole levemente desgastada, pequenas anotações a lápis no prefácio, mas sem nenhuma rasura no resto do livro.',
    city: 'Cabinda',
    state: 'CA'
  },
  {
    id: 'book-14',
    title: 'Pai Rico, Pai Pobre',
    authorId: 'aut-9',
    categoryId: 'cat-4',
    description: 'Este livro clássico e revolucionário de inteligência de investimentos quebra o mito de que você precisa ganhar uma fortuna para se tornar rico e mostra aos pais o que ensinar sobre ativos de caixa.',
    price: 12000,
    rating: 4.8,
    coverImage: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-blue-700 via-sky-850 to-slate-950',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 15,
    pages: 336,
    publishedDate: '1997-04-01',
    bestSeller: true,
    newRelease: false,
    reviewsCount: 512,
    isbn: '978-85-508-0148-3',
    publisher: 'Alta Books Finanças',
    sellerType: 'bookstore',
    sellerName: 'Livraria Sorte Comum',
    city: 'Luanda',
    state: 'LA'
  },
  {
    id: 'book-15',
    title: 'O Homem Mais Rico da Babilónia',
    authorId: 'aut-9',
    categoryId: 'cat-4',
    description: 'Famosas lições milenares condensadas em parábolas atemporais que ensinam a poupar pelo menos um décimo do salário, proteger o dinheiro contra perdas e fazê-lo frutificar vigorosamente.',
    price: 6000,
    rating: 4.7,
    coverImage: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=450&auto=format&fit=crop&q=80',
    coverColor: 'from-amber-600 via-stone-850 to-neutral-900',
    type: 'digital',
    formats: ['pdf', 'epub'],
    stock: 999,
    pages: 160,
    publishedDate: '1926-06-04',
    bestSeller: false,
    newRelease: false,
    reviewsCount: 145,
    isbn: '978-85-9508-153-5',
    publisher: 'HarperCollins Angola',
    sellerType: 'author',
    sellerName: 'Robert Kiyosaki'
  },
  {
    id: 'book-16',
    title: 'O Cão e os Caluandas',
    authorId: 'aut-1',
    categoryId: 'cat-1',
    description: 'Um clássico do escritor angolano Pepetela, que acompanha a trajetória de um cão pastor alemão pelas ruas e musseques de Luanda nos anos pós-independência, servindo de elo de ligação entre diferentes estratos sociais e revelando os desafios, sonhos e dilemas da sociedade angolana com sensibilidade e humor refinado.',
    price: 6805,
    rating: 4.8,
    coverImage: 'https://www.kapulana.com.br/wp-content/uploads/2016/10/O-c%C3%A3o-e-os-caluandas_Capa.jpg',
    coverColor: 'from-blue-600 via-sky-500 to-amber-500',
    type: 'both',
    formats: ['physical', 'pdf', 'epub'],
    stock: 20,
    pages: 184,
    publishedDate: '1985-11-20',
    bestSeller: false,
    newRelease: true,
    reviewsCount: 43,
    isbn: '978-85-68855-05-8',
    publisher: 'Editora Mulemba',
    sellerType: 'publisher',
    sellerName: 'Editora Mulemba'
  }
];

export const mockReviews: Review[] = [
  {
    id: 'rev-1',
    bookId: 'book-1',
    userName: 'Kalandula Santos',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Uma leitura absolutamente obrigatória para compreender a essência do combate angolano. O retrato político e humano feito por Pepetela continua assustadoramente atual. Emocionei-me do início ao fim.',
    date: '2026-03-04'
  },
  {
    id: 'rev-2',
    bookId: 'book-1',
    userName: 'Mariana Benguela',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=80',
    rating: 4,
    comment: 'Muito expressivo. Captura muito bem a psicologia dos guerrilheiros no Mayombe. As descrições arbóreas são fantásticas, apenas desacelera de leve no meio, mas o clímax compensa tudo.',
    date: '2026-04-12'
  },
  {
    id: 'rev-3',
    bookId: 'book-10',
    userName: 'Pedro Mateus (Eng. Luanda)',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Este livro mudou completamente a minha forma de programar e organizar funções. Ideal para programadores juniores e seniores que buscam escrever sistemas modulares em Luanda.',
    date: '2026-05-18'
  },
  {
    id: 'rev-4',
    bookId: 'book-12',
    userName: 'Cláudia Huambo',
    userAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'James Clear criou um método brilhante. Implementei as pequenas mudanças de 1% nas minhas leituras noturnas e os resultados em foco têm sido incríveis!',
    date: '2026-05-24'
  },
  {
    id: 'rev-5',
    bookId: 'book-16',
    userName: 'Afonso Luanda',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&auto=format&fit=crop&q=80',
    rating: 5,
    comment: 'Maravilhoso! Pepetela usa a peregrinação de um cão para nos guiar por Luanda com uma ironia fina e tocante. A edição da Livraria Mulemba física é impecável.',
    date: '2026-06-01'
  }
];

export const mockPromoCodes: { [key: string]: number } = {
  'MULEMBA20': 0.20,
  'BOOKVERSE20': 0.20,
  'BEMVINDO10': 0.10,
  'LEITURA5': 5000.00, // Flat discount in Kwanza
};
